iCargopoc/components

spreadsheet/src/components/slickgrid.js, spreadsheet/src/scss/iCargo.scss
CSS changes and date picker added in spreadsheet
=> CSS changes and datapicker added

spreadsheet/src/App.js, spreadsheet/src/components/slickgrid.js
changes with sorting are added.
reverted back to .js
the function name reverted back to Spreadsheet.
=> changes with sorting are updated

grid/src/App.js, grid/src/DetailsEdit.js, grid/src/QueuedBookingEdit.js, grid/src/RevenueEdit.js, grid/src/UldPositionsEdit.js, grid/src/VolumeEdit.js, grid/src/WeigthEdit.js
Cell Edit has been implemented in all columns except UldPositions
=> Added Cell Edit in All Columns except UldPositions Column

spreadsheet/src/components/datagrid/datagrid.js, spreadsheet/src/stubs/sample-data.json
1. Made changes for editing the cell
2. Dragging the values from top to bottom as like spreadsheet
3. Implemented data grid by removing length issue by deprecating package file
=> Sample data's added for checking purpose

spreadsheet/src/App.js, spreadsheet/src/components/Header/Header.js, spreadsheet/src/components/datagrid/datagrid.js
added the global search(filter) feature
=> added the global search(filter) feature

spreadsheet/src/App.js, spreadsheet/src/components/common/Header.js, spreadsheet/src/components/datagrid/datagrid.js
=> added column sorting

grid/src/FlightEdit.js
Date Picker implemented in Flight Column
=> Cell Edit For Flight Column: Calendar Drop Down

grid/src/App.js, grid/src/UldPositionsEdit.js
All changes for Uldposition Cell Edit implemented and Tested
=> UldPosition Cell Edit: Completed

spreadsheet/src/App.js, spreadsheet/src/components/common/LoadingSpinner.js, spreadsheet/src/components/datagrid/datagrid.js
Adding copy, paste functionality
Added bold, italic functions but still issue is pending
=> Adding copy,paste functionality and bold issue pending

filter/package-lock.json, filter/package.json, filter/src/App.js, filter/src/index.js, filter/src/scss/filter.scss
New filter component design completed
Minor alignment issues are pending
=> New filter component design

filter/src/App.js, filter/src/components/LeftSideDrawer.js, filter/src/components/RightSideDrawer.js, filter/src/scss/filter.scss
Added new components such as left and right sidedrawer.
Modified SCSS
=> Filter component functions

filter/package-lock.json, filter/package.json, filter/src/App.js, filter/src/components/LeftSideDrawer.js, filter/src/components/RightSideDrawer.js, filter/src/components/SideDrawer.js, filter/src/scss/filter.scss
Created separate component
Hiding function is done but showing needs to be work on
SCSS fixes are added
=> Separated components for showing/hiding

filter/src/App.js, filter/src/components/RightSideDrawer.js
solved the closing issue in right side panel
=> solved the closing issue in right side panel

filter/src/App.js, filter/src/components/RightSideDrawer.js, filter/src/scss/filter.scss
Changes on Design for right side drawer
Classes added on right side drawer
=> Changes on design

filter/src/App.js, filter/src/components/List/List.js, filter/src/components/List/Lists.js, filter/src/components/drawer/leftdrawer.js, filter/src/components/drawer/rightdrawer.js, filter/src/components/types/PortTypes/airport.js, filter/src/components/types/PortTypes/airportGroup.js, filter/src/components/types/PortTypes/city.js, filter/src/components/types/PortTypes/cityGroup.js, filter/src/components/types/PortTypes/country.js, filter/src/components/types/arrivalport.js, filter/src/components/types/date.js, filter/src/components/types/departureport.js, filter/src/components/types/revenue.js, filter/src/scss/filter.scss
Components added for list view.
Conflicts fixed
=> Spreadsheet poc

filter/src/App.js, filter/src/components/drawer/rightdrawer.js, filter/src/components/panel/AppliedFilterPanel.js, filter/src/components/types/PortTypes/airport.js, filter/src/components/types/departureport.js
Conflict fixed for airport nd departure port
List filters component fixed
=> Fixes for listandsavedfilter panel nd conflict fixes

filter/src/components/drawer/rightdrawer.js, filter/src/components/panel/SavedFilters.js
=> updated save and apply filter

filter/src/App.js, filter/src/components/drawer/leftdrawer.js, filter/src/components/drawer/rightdrawer.js, filter/src/components/types/PortTypes/airportGroup.js, filter/src/components/types/PortTypes/city.js, filter/src/components/types/PortTypes/cityGroup.js, filter/src/components/types/PortTypes/country.js, filter/src/components/types/date.js, filter/src/components/types/revenue.js, filter/src/savedfilters/flights-under-FRA-departureport.json
updated the structured savedFilter
=> updated the structured savedFilter

filter/src/scss/filter.scss
CSS Changes made as per design
=> CSS changes

filter/src/App.js, filter/src/components/drawer/rightdrawer.js, filter/src/spreadSheet/SpeadSheet.js
=> applyFilterClose

filter/src/components/drawer/leftdrawer.js, filter/src/components/drawer/rightdrawer.js, filter/src/components/panel/MainFilterPanel.js, filter/src/components/panel/SavedFilters.js, filter/src/scss/filter.scss
Left Drawer Search, filter save validation,outside click with Saved Filter List
=> Left Drawer Search, filter save validation,outside click with Saved Filter List

filter/src/App.js, filter/src/components/drawer/leftdrawer.js, filter/src/components/drawer/rightdrawer.js, filter/src/components/panel/MainFilterPanel.js, filter/src/components/panel/SavedFilters.js, filter/src/components/types/date.js, filter/src/components/types/porttypes/airport.js, filter/src/components/types/porttypes/airportGroup.js, filter/src/components/types/porttypes/city.js, filter/src/components/types/porttypes/cityGroup.js, filter/src/components/types/porttypes/country.js, filter/src/components/types/revenue.js, filter/src/stubs/FilterData.json
Limiting the saved filterList, binding saved filter and drawer
=> Limiting the saved filterList, binding saved filter and drawer

filter/src/components/drawer/rightdrawer.js, filter/src/components/types/arrivalport.js, filter/src/components/types/departureport.js, filter/src/components/types/porttypes/airport.js, filter/src/components/types/porttypes/airportGroup.js, filter/src/components/types/porttypes/city.js, filter/src/components/types/porttypes/cityGroup.js, filter/src/components/types/porttypes/country.js
updates Departure and Arrival Airports
=> updates Departure and Arrival Airports 

spreadsheet/src/App.js, spreadsheet/src/components/SpreadSheet.js, spreadsheet/src/components/functions/DatePicker.js, spreadsheet/src/components/overlays/export_data/ExportData.js
=> build update

spreadsheet/src/components/SpreadSheet.js
update on mapping the airportcodes
=> update on mapping the airportcodes
